    <style type="text/css" media="all"><!--@import "css/style.css";--></style>
    <meta content="text/html; charset=ISO-8859-1" http-equiv="content-type" />
    <meta name="description" content="Tete is an ear trainer developed in Java.  It aid ear training for interval, chords, and scales.  It can test the user's ability to recognise these patterns." />
    <meta name="keywords" content="ear training, ear trainer, pitch, intervals, chords, scales, notes, relative, tete, java, midi, arpeggio, open source, LGPL, freeware, mipper" />

