    <div id="menu">
      <ul>
        <li><a href="index.shtml" name="home">Home</a></li>
        <li><a href="tutorial.shtml" name="screens">Tutorial</a></li>
        <li><a href="todo.shtml" name="todo">To Do</a></li>
        <li><a href="links.shtml" name="links">Links</a></li>
        <li><a href="http://sourceforge.net/projects/tete" name="download">Download</a></li>
      </ul>
    </div>

