      <div id="footer">
        <a href="http://www.spreadfirefox.com/?q=affiliates&amp;id=0&amp;t=62"><img border="0" alt="Get Firefox!" title="Get Firefox!" src="http://sfx-images.mozilla.org/affiliates/Buttons/110x32/take.gif"/></a>
        <a href="http://sourceforge.net"><img src="http://sourceforge.net/sflogo.php?group_id=147629&amp;type=1" alt="SourceForge.net Logo" border="0" height="31" width="88"></a>
        <a href="http://sourceforge.net/donate/index.php?group_id=147629"><img src="http://images.sourceforge.net/images/project-support.jpg" width="88" height="32" border="0" alt="Support Tete" /> </a>
      </div>

